services:

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 321
      POSTGRES_DB: game_launcher
    volumes:
        - postgres_data:/var/lib/postgresql
        #- postgres_data:/var/lib/postgresql/data
    networks:
      - game_launcher-net

  backend:
    image: eclipse-temurin:25-jdk
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/game_launcher
      DATABASE_USER: root
      DATABASE_PASSWORD: 321
      DATABASE_DB: game_launcher
    volumes:
      - ./backend:/backend
    depends_on:
      - postgresql
    networks:
      - game_launcher-net
    working_dir: /backend
    command: ["sh", "-c", "chmod +x gradlew && ./gradlew bootRun"]

  frontend:
    image: node:latest
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
    command: ["sh", "-c", "cd /frontend && npm install && npm start"]

networks:
  game_launcher-net:
    driver: bridge

volumes:
  postgres_data:
